#todo : 작성중
#https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3

version: "3.8"
services:
  mongodb:
    image: 'mongo:4.2'
    container_name: 'mongodb-books-gogo'
    environment:
      - MONGO_INITDB_DATABASE=books-gogo-taskman
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ${HOME}/data/docker/books_gogo_mongodb:/data/db
    ports:
      - 27017:27017